#!/bin/sh

LIB_NAME=clinked-list

ensure_dir() {
  if [ ! -d $1 ]; then
    mkdir $1
  fi
}

ensure_dir "target";
ensure_dir "bin";
cd target;

ensure_dir "cvec";
cd cvec;
gcc -Wall -g -c ../../include/cvec/lib/*.c;
cd ..;

gcc -Wall -g -c ../src/*.c;
ar -rc "./lib$LIB_NAME.a" ./cvec/*.o *.o;

rm -rf cvec;
rm -f *.o
